# Generated by Django 2.0.13 on 2019-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Надо сделать', 'Надо сделать'), ('Сделано', 'Сделано'), ('Отменено', 'Отменено')], default='Надо сделать', max_length=10),
        ),
    ]
