# Generated by Django 2.0.13 on 2019-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190306_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Надо сделать', 'Надо сделать'), ('Сделано', 'Сделано'), ('Отменено', 'Отменено')], default='Надо сделать', max_length=15),
        ),
    ]
